#+STARTUP: content logdone hideblocks
#+TODO: TASK(t!) | DONE(d) CANCEL(c)
#+TODO: BUG(b!) | FIXED(f) REJECT(r)
#+PRIORITIES: A F C
#+TAGS: current(c) testing(t)
#+CONSTANTS: last_issue_id=4

* Задачи
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив задач
  :END:

** TASK Сделать подсказку границы между годами
   :PROPERTIES:
   :issue_id: 1
   :issue_type: task
   :END:
   <2017-01-12 Чт>

   [2017-01-12 Чт]

   Иногда надо узнать, где граница между годами, и приходится
   проматывать вручную. Возможно, в статусной строке это надо сделать
   или ещё как-нибудь.

** TASK Сделать юнит-тесты для вычислителей
   :PROPERTIES:
   :issue_id: 2
   :issue_type: task
   :END:
   <2017-02-05 Вс>

   [2017-02-05 Вс]

   Без юнит-тестов невозможно понять, что работает, а что нет. Хотя бы
   минимальные тесты должны быть, и вообще должна быть возможность при
   обнаружении бага исправить его и подчеркнуть надёжность исправления
   через юнит-тест.

   [2018-04-04 Ср]

   Добавил инфраструктуру для юнит-тестов.


* Баги
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив багов
  :END:

** FIXED Неправильно определяет границу 2017 года
   CLOSED: [2017-02-05 Вс 13:09]
   :PROPERTIES:
   :issue_id: 3
   :issue_type: bug
   :END:
   <2017-02-05 Вс>

   [2017-02-05 Вс]

   Должно быть 2017-01-28, а он ставит 2017-02-20.

   Если поставить 2017-01-27 и вычислить, он правильно ставит.
   Если поставить 2017-01-28 и вычислить, он правильно ставит.
   Если же поставить 2017-02-01 и вычислить, он неправильно ставит.

   [2017-02-05 Вс]

   Дело оказалось в неправильном сравнении дат. Сравнивался либо
   месяц, либо день. Поэтому при правильном месяце и неправильном дне
   считалось, что и месяц и день неправильные.


* Окружение
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив окружения
  :END:
